# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'VGSCollectSDK', '1.16.3'
  pod 'VGSCollectSDK/BlinkCard', '1.16.3'
  pod 'VGSShowSDK', '1.2.1'

end
