# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'VGSCollectSDK'
  pod 'VGSShowSDK'

	# Add CardIO module to use Card.io as scan provider
	pod 'VGSCollectSDK/CardIO' 

end
